server:
  port: 8089
  servlet:
    session:
      timeout: 30m #30分钟，测试的话时间不能太短，否则不准。m(分钟)，s(秒)，h(小时)，不写单位默认毫秒
spring:
  application:
    name: springboot-mini
  datasource:
    url: jdbc:mysql://192.168.19.128:3306/test_data?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql2022
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.learning.springboot.entity
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.learning.springboot.dao: debug

jenkins:
  url: http://192.168.19.128:8080
  username: admin
  password: admin
  #命令运行的测试用例类型 1 文本 2 文件
  casetype: 2
  casesuffix: yml
  testcommand: hrun
  callbackurl: http://192.168.19.128:8091
testUSer:
  key1: Hogwarts
